export const colleges = [
  { name: "University of Alabama", city: "Tuscaloosa", state: "AL", airportCode: "BHM", airportName: "Birmingham-Shuttlesworth International Airport", airportDistanceMiles: 59 },
  { name: "Auburn University", city: "Auburn", state: "AL", airportCode: "ATL", airportName: "Hartsfield-Jackson Atlanta International Airport", airportDistanceMiles: 105 },
  { name: "University of Alabama at Birmingham", city: "Birmingham", state: "AL", airportCode: "BHM", airportName: "Birmingham-Shuttlesworth International Airport", airportDistanceMiles: 6 },
  { name: "University of South Alabama", city: "Mobile", state: "AL", airportCode: "MOB", airportName: "Mobile Regional Airport", airportDistanceMiles: 11 },
  { name: "Samford University", city: "Birmingham", state: "AL", airportCode: "BHM", airportName: "Birmingham-Shuttlesworth International Airport", airportDistanceMiles: 8 },
  { name: "University of Alaska Anchorage", city: "Anchorage", state: "AK", airportCode: "ANC", airportName: "Ted Stevens Anchorage International Airport", airportDistanceMiles: 5 },
  { name: "University of Alaska Fairbanks", city: "Fairbanks", state: "AK", airportCode: "FAI", airportName: "Fairbanks International Airport", airportDistanceMiles: 4 },
  { name: "Arizona State University", city: "Tempe", state: "AZ", airportCode: "PHX", airportName: "Phoenix Sky Harbor International Airport", airportDistanceMiles: 7 },
  { name: "University of Arizona", city: "Tucson", state: "AZ", airportCode: "TUS", airportName: "Tucson International Airport", airportDistanceMiles: 9 },
  { name: "Northern Arizona University", city: "Flagstaff", state: "AZ", airportCode: "PHX", airportName: "Phoenix Sky Harbor International Airport", airportDistanceMiles: 145 },
  { name: "University of Arkansas", city: "Fayetteville", state: "AR", airportCode: "XNA", airportName: "Northwest Arkansas National Airport", airportDistanceMiles: 24 },
  { name: "Arkansas State University", city: "Jonesboro", state: "AR", airportCode: "MEM", airportName: "Memphis International Airport", airportDistanceMiles: 78 },
  { name: "University of Central Arkansas", city: "Conway", state: "AR", airportCode: "LIT", airportName: "Clinton National Airport", airportDistanceMiles: 37 },
  { name: "University of California, Berkeley", city: "Berkeley", state: "CA", airportCode: "OAK", airportName: "Oakland International Airport", airportDistanceMiles: 15 },
  { name: "University of California, Davis", city: "Davis", state: "CA", airportCode: "SMF", airportName: "Sacramento International Airport", airportDistanceMiles: 21 },
  { name: "University of California, Irvine", city: "Irvine", state: "CA", airportCode: "SNA", airportName: "John Wayne Airport", airportDistanceMiles: 5 },
  { name: "University of California, Los Angeles", city: "Los Angeles", state: "CA", airportCode: "LAX", airportName: "Los Angeles International Airport", airportDistanceMiles: 13 },
  { name: "University of California, Riverside", city: "Riverside", state: "CA", airportCode: "ONT", airportName: "Ontario International Airport", airportDistanceMiles: 19 },
  { name: "University of California, San Diego", city: "San Diego", state: "CA", airportCode: "SAN", airportName: "San Diego International Airport", airportDistanceMiles: 10 },
  { name: "University of California, Santa Barbara", city: "Santa Barbara", state: "CA", airportCode: "SBA", airportName: "Santa Barbara Airport", airportDistanceMiles: 7 },
  { name: "University of Southern California", city: "Los Angeles", state: "CA", airportCode: "LAX", airportName: "Los Angeles International Airport", airportDistanceMiles: 16 },
  { name: "Stanford University", city: "Stanford", state: "CA", airportCode: "SFO", airportName: "San Francisco International Airport", airportDistanceMiles: 21 },
  { name: "San Diego State University", city: "San Diego", state: "CA", airportCode: "SAN", airportName: "San Diego International Airport", airportDistanceMiles: 9 },
  { name: "University of Colorado Boulder", city: "Boulder", state: "CO", airportCode: "DEN", airportName: "Denver International Airport", airportDistanceMiles: 42 },
  { name: "Colorado State University", city: "Fort Collins", state: "CO", airportCode: "DEN", airportName: "Denver International Airport", airportDistanceMiles: 69 },
  { name: "University of Denver", city: "Denver", state: "CO", airportCode: "DEN", airportName: "Denver International Airport", airportDistanceMiles: 25 },
  { name: "University of Connecticut", city: "Storrs", state: "CT", airportCode: "BDL", airportName: "Bradley International Airport", airportDistanceMiles: 37 },
  { name: "Yale University", city: "New Haven", state: "CT", airportCode: "BDL", airportName: "Bradley International Airport", airportDistanceMiles: 53 },
  { name: "University of Delaware", city: "Newark", state: "DE", airportCode: "PHL", airportName: "Philadelphia International Airport", airportDistanceMiles: 35 },
  { name: "University of Florida", city: "Gainesville", state: "FL", airportCode: "GNV", airportName: "Gainesville Regional Airport", airportDistanceMiles: 5 },
  { name: "Florida State University", city: "Tallahassee", state: "FL", airportCode: "TLH", airportName: "Tallahassee International Airport", airportDistanceMiles: 6 },
  { name: "University of Central Florida", city: "Orlando", state: "FL", airportCode: "MCO", airportName: "Orlando International Airport", airportDistanceMiles: 18 },
  { name: "University of South Florida", city: "Tampa", state: "FL", airportCode: "TPA", airportName: "Tampa International Airport", airportDistanceMiles: 14 },
  { name: "Florida International University", city: "Miami", state: "FL", airportCode: "MIA", airportName: "Miami International Airport", airportDistanceMiles: 9 },
  { name: "University of Miami", city: "Coral Gables", state: "FL", airportCode: "MIA", airportName: "Miami International Airport", airportDistanceMiles: 6 },
  { name: "Florida Atlantic University", city: "Boca Raton", state: "FL", airportCode: "FLL", airportName: "Fort Lauderdale-Hollywood International Airport", airportDistanceMiles: 27 },
  { name: "University of North Florida", city: "Jacksonville", state: "FL", airportCode: "JAX", airportName: "Jacksonville International Airport", airportDistanceMiles: 21 },
  { name: "University of Georgia", city: "Athens", state: "GA", airportCode: "ATL", airportName: "Hartsfield-Jackson Atlanta International Airport", airportDistanceMiles: 78 },
  { name: "Georgia Institute of Technology", city: "Atlanta", state: "GA", airportCode: "ATL", airportName: "Hartsfield-Jackson Atlanta International Airport", airportDistanceMiles: 13 },
  { name: "Georgia State University", city: "Atlanta", state: "GA", airportCode: "ATL", airportName: "Hartsfield-Jackson Atlanta International Airport", airportDistanceMiles: 11 },
  { name: "Emory University", city: "Atlanta", state: "GA", airportCode: "ATL", airportName: "Hartsfield-Jackson Atlanta International Airport", airportDistanceMiles: 17 },
  { name: "University of Hawaii at Manoa", city: "Honolulu", state: "HI", airportCode: "HNL", airportName: "Daniel K. Inouye International Airport", airportDistanceMiles: 9 },
  { name: "Boise State University", city: "Boise", state: "ID", airportCode: "BOI", airportName: "Boise Airport", airportDistanceMiles: 5 },
  { name: "University of Idaho", city: "Moscow", state: "ID", airportCode: "GEG", airportName: "Spokane International Airport", airportDistanceMiles: 91 },
  { name: "University of Illinois Urbana-Champaign", city: "Champaign", state: "IL", airportCode: "CMI", airportName: "University of Illinois Willard Airport", airportDistanceMiles: 6 },
  { name: "Northwestern University", city: "Evanston", state: "IL", airportCode: "ORD", airportName: "Chicago O'Hare International Airport", airportDistanceMiles: 16 },
  { name: "University of Chicago", city: "Chicago", state: "IL", airportCode: "MDW", airportName: "Chicago Midway International Airport", airportDistanceMiles: 10 },
  { name: "Illinois State University", city: "Normal", state: "IL", airportCode: "BMI", airportName: "Central Illinois Regional Airport", airportDistanceMiles: 5 },
  { name: "DePaul University", city: "Chicago", state: "IL", airportCode: "ORD", airportName: "Chicago O'Hare International Airport", airportDistanceMiles: 17 },
  { name: "University of Notre Dame", city: "Notre Dame", state: "IN", airportCode: "SBN", airportName: "South Bend International Airport", airportDistanceMiles: 5 },
  { name: "Indiana University Bloomington", city: "Bloomington", state: "IN", airportCode: "IND", airportName: "Indianapolis International Airport", airportDistanceMiles: 48 },
  { name: "Purdue University", city: "West Lafayette", state: "IN", airportCode: "IND", airportName: "Indianapolis International Airport", airportDistanceMiles: 69 },
  { name: "Ball State University", city: "Muncie", state: "IN", airportCode: "IND", airportName: "Indianapolis International Airport", airportDistanceMiles: 57 },
  { name: "University of Iowa", city: "Iowa City", state: "IA", airportCode: "CID", airportName: "The Eastern Iowa Airport", airportDistanceMiles: 24 },
  { name: "Iowa State University", city: "Ames", state: "IA", airportCode: "DSM", airportName: "Des Moines International Airport", airportDistanceMiles: 39 },
  { name: "University of Kansas", city: "Lawrence", state: "KS", airportCode: "MCI", airportName: "Kansas City International Airport", airportDistanceMiles: 47 },
  { name: "Kansas State University", city: "Manhattan", state: "KS", airportCode: "MHK", airportName: "Manhattan Regional Airport", airportDistanceMiles: 8 },
  { name: "Wichita State University", city: "Wichita", state: "KS", airportCode: "ICT", airportName: "Wichita Dwight D. Eisenhower National Airport", airportDistanceMiles: 8 },
  { name: "University of Kentucky", city: "Lexington", state: "KY", airportCode: "LEX", airportName: "Blue Grass Airport", airportDistanceMiles: 7 },
  { name: "University of Louisville", city: "Louisville", state: "KY", airportCode: "SDF", airportName: "Louisville Muhammad Ali International Airport", airportDistanceMiles: 6 },
  { name: "Western Kentucky University", city: "Bowling Green", state: "KY", airportCode: "BNA", airportName: "Nashville International Airport", airportDistanceMiles: 67 },
  { name: "Louisiana State University", city: "Baton Rouge", state: "LA", airportCode: "BTR", airportName: "Baton Rouge Metropolitan Airport", airportDistanceMiles: 10 },
  { name: "Tulane University", city: "New Orleans", state: "LA", airportCode: "MSY", airportName: "Louis Armstrong New Orleans International Airport", airportDistanceMiles: 15 },
  { name: "University of Louisiana at Lafayette", city: "Lafayette", state: "LA", airportCode: "LFT", airportName: "Lafayette Regional Airport", airportDistanceMiles: 4 },
  { name: "University of Maine", city: "Orono", state: "ME", airportCode: "BGR", airportName: "Bangor International Airport", airportDistanceMiles: 10 },
  { name: "Bowdoin College", city: "Brunswick", state: "ME", airportCode: "PWM", airportName: "Portland International Jetport", airportDistanceMiles: 33 },
  { name: "University of Maryland, College Park", city: "College Park", state: "MD", airportCode: "BWI", airportName: "Baltimore/Washington International Thurgood Marshall Airport", airportDistanceMiles: 25 },
  { name: "Johns Hopkins University", city: "Baltimore", state: "MD", airportCode: "BWI", airportName: "Baltimore/Washington International Thurgood Marshall Airport", airportDistanceMiles: 14 },
  { name: "Towson University", city: "Towson", state: "MD", airportCode: "BWI", airportName: "Baltimore/Washington International Thurgood Marshall Airport", airportDistanceMiles: 20 },
  { name: "University of Massachusetts Amherst", city: "Amherst", state: "MA", airportCode: "BDL", airportName: "Bradley International Airport", airportDistanceMiles: 46 },
  { name: "Boston University", city: "Boston", state: "MA", airportCode: "BOS", airportName: "Logan International Airport", airportDistanceMiles: 6 },
  { name: "Harvard University", city: "Cambridge", state: "MA", airportCode: "BOS", airportName: "Logan International Airport", airportDistanceMiles: 7 },
  { name: "Massachusetts Institute of Technology", city: "Cambridge", state: "MA", airportCode: "BOS", airportName: "Logan International Airport", airportDistanceMiles: 6 },
  { name: "Northeastern University", city: "Boston", state: "MA", airportCode: "BOS", airportName: "Logan International Airport", airportDistanceMiles: 7 },
  { name: "University of Michigan", city: "Ann Arbor", state: "MI", airportCode: "DTW", airportName: "Detroit Metropolitan Wayne County Airport", airportDistanceMiles: 25 },
  { name: "Michigan State University", city: "East Lansing", state: "MI", airportCode: "LAN", airportName: "Capital Region International Airport", airportDistanceMiles: 8 },
  { name: "Wayne State University", city: "Detroit", state: "MI", airportCode: "DTW", airportName: "Detroit Metropolitan Wayne County Airport", airportDistanceMiles: 21 },
  { name: "Western Michigan University", city: "Kalamazoo", state: "MI", airportCode: "AZO", airportName: "Kalamazoo/Battle Creek International Airport", airportDistanceMiles: 4 },
  { name: "University of Minnesota Twin Cities", city: "Minneapolis", state: "MN", airportCode: "MSP", airportName: "Minneapolis-Saint Paul International Airport", airportDistanceMiles: 10 },
  { name: "Carleton College", city: "Northfield", state: "MN", airportCode: "MSP", airportName: "Minneapolis-Saint Paul International Airport", airportDistanceMiles: 41 },
  { name: "University of Mississippi", city: "Oxford", state: "MS", airportCode: "MEM", airportName: "Memphis International Airport", airportDistanceMiles: 74 },
  { name: "Mississippi State University", city: "Starkville", state: "MS", airportCode: "GTR", airportName: "Golden Triangle Regional Airport", airportDistanceMiles: 17 },
  { name: "University of Southern Mississippi", city: "Hattiesburg", state: "MS", airportCode: "GPT", airportName: "Gulfport-Biloxi International Airport", airportDistanceMiles: 72 },
  { name: "University of Missouri", city: "Columbia", state: "MO", airportCode: "STL", airportName: "St. Louis Lambert International Airport", airportDistanceMiles: 125 },
  { name: "Washington University in St. Louis", city: "St. Louis", state: "MO", airportCode: "STL", airportName: "St. Louis Lambert International Airport", airportDistanceMiles: 8 },
  { name: "Missouri State University", city: "Springfield", state: "MO", airportCode: "SGF", airportName: "Springfield-Branson National Airport", airportDistanceMiles: 10 },
  { name: "Saint Louis University", city: "St. Louis", state: "MO", airportCode: "STL", airportName: "St. Louis Lambert International Airport", airportDistanceMiles: 14 },
  { name: "University of Montana", city: "Missoula", state: "MT", airportCode: "MSO", airportName: "Missoula Montana Airport", airportDistanceMiles: 7 },
  { name: "Montana State University", city: "Bozeman", state: "MT", airportCode: "BZN", airportName: "Bozeman Yellowstone International Airport", airportDistanceMiles: 9 },
  { name: "University of Nebraska-Lincoln", city: "Lincoln", state: "NE", airportCode: "LNK", airportName: "Lincoln Airport", airportDistanceMiles: 6 },
  { name: "Creighton University", city: "Omaha", state: "NE", airportCode: "OMA", airportName: "Eppley Airfield", airportDistanceMiles: 5 },
  { name: "University of Nevada, Las Vegas", city: "Las Vegas", state: "NV", airportCode: "LAS", airportName: "Harry Reid International Airport", airportDistanceMiles: 4 },
  { name: "University of Nevada, Reno", city: "Reno", state: "NV", airportCode: "RNO", airportName: "Reno-Tahoe International Airport", airportDistanceMiles: 4 },
  { name: "Dartmouth College", city: "Hanover", state: "NH", airportCode: "BOS", airportName: "Logan International Airport", airportDistanceMiles: 130 },
  { name: "University of New Hampshire", city: "Durham", state: "NH", airportCode: "MHT", airportName: "Manchester-Boston Regional Airport", airportDistanceMiles: 43 },
  { name: "Princeton University", city: "Princeton", state: "NJ", airportCode: "EWR", airportName: "Newark Liberty International Airport", airportDistanceMiles: 41 },
  { name: "Rutgers University-New Brunswick", city: "New Brunswick", state: "NJ", airportCode: "EWR", airportName: "Newark Liberty International Airport", airportDistanceMiles: 26 },
  { name: "Seton Hall University", city: "South Orange", state: "NJ", airportCode: "EWR", airportName: "Newark Liberty International Airport", airportDistanceMiles: 8 },
  { name: "New Jersey Institute of Technology", city: "Newark", state: "NJ", airportCode: "EWR", airportName: "Newark Liberty International Airport", airportDistanceMiles: 6 },
  { name: "University of New Mexico", city: "Albuquerque", state: "NM", airportCode: "ABQ", airportName: "Albuquerque International Sunport", airportDistanceMiles: 6 },
  { name: "New Mexico State University", city: "Las Cruces", state: "NM", airportCode: "ELP", airportName: "El Paso International Airport", airportDistanceMiles: 51 },
  { name: "Columbia University", city: "New York", state: "NY", airportCode: "LGA", airportName: "LaGuardia Airport", airportDistanceMiles: 10 },
  { name: "New York University", city: "New York", state: "NY", airportCode: "LGA", airportName: "LaGuardia Airport", airportDistanceMiles: 11 },
  { name: "Cornell University", city: "Ithaca", state: "NY", airportCode: "ITH", airportName: "Ithaca Tompkins International Airport", airportDistanceMiles: 5 },
  { name: "Syracuse University", city: "Syracuse", state: "NY", airportCode: "SYR", airportName: "Syracuse Hancock International Airport", airportDistanceMiles: 9 },
  { name: "University at Buffalo", city: "Buffalo", state: "NY", airportCode: "BUF", airportName: "Buffalo Niagara International Airport", airportDistanceMiles: 11 },
  { name: "University of Rochester", city: "Rochester", state: "NY", airportCode: "ROC", airportName: "Frederick Douglass Greater Rochester International Airport", airportDistanceMiles: 5 },
  { name: "Fordham University", city: "Bronx", state: "NY", airportCode: "LGA", airportName: "LaGuardia Airport", airportDistanceMiles: 9 },
  { name: "Stony Brook University", city: "Stony Brook", state: "NY", airportCode: "JFK", airportName: "John F. Kennedy International Airport", airportDistanceMiles: 45 },
  { name: "University of North Carolina at Chapel Hill", city: "Chapel Hill", state: "NC", airportCode: "RDU", airportName: "Raleigh-Durham International Airport", airportDistanceMiles: 18 },
  { name: "Duke University", city: "Durham", state: "NC", airportCode: "RDU", airportName: "Raleigh-Durham International Airport", airportDistanceMiles: 17 },
  { name: "North Carolina State University", city: "Raleigh", state: "NC", airportCode: "RDU", airportName: "Raleigh-Durham International Airport", airportDistanceMiles: 11 },
  { name: "Wake Forest University", city: "Winston-Salem", state: "NC", airportCode: "GSO", airportName: "Piedmont Triad International Airport", airportDistanceMiles: 23 },
  { name: "East Carolina University", city: "Greenville", state: "NC", airportCode: "RDU", airportName: "Raleigh-Durham International Airport", airportDistanceMiles: 87 },
  { name: "University of North Dakota", city: "Grand Forks", state: "ND", airportCode: "GFK", airportName: "Grand Forks International Airport", airportDistanceMiles: 7 },
  { name: "North Dakota State University", city: "Fargo", state: "ND", airportCode: "FAR", airportName: "Hector International Airport", airportDistanceMiles: 5 },
  { name: "Ohio State University", city: "Columbus", state: "OH", airportCode: "CMH", airportName: "John Glenn Columbus International Airport", airportDistanceMiles: 10 },
  { name: "University of Cincinnati", city: "Cincinnati", state: "OH", airportCode: "CVG", airportName: "Cincinnati/Northern Kentucky International Airport", airportDistanceMiles: 17 },
  { name: "University of Dayton", city: "Dayton", state: "OH", airportCode: "DAY", airportName: "Dayton International Airport", airportDistanceMiles: 14 },
  { name: "Case Western Reserve University", city: "Cleveland", state: "OH", airportCode: "CLE", airportName: "Cleveland Hopkins International Airport", airportDistanceMiles: 17 },
  { name: "Miami University", city: "Oxford", state: "OH", airportCode: "CVG", airportName: "Cincinnati/Northern Kentucky International Airport", airportDistanceMiles: 43 },
  { name: "University of Oklahoma", city: "Norman", state: "OK", airportCode: "OKC", airportName: "Will Rogers World Airport", airportDistanceMiles: 22 },
  { name: "Oklahoma State University", city: "Stillwater", state: "OK", airportCode: "OKC", airportName: "Will Rogers World Airport", airportDistanceMiles: 73 },
  { name: "University of Tulsa", city: "Tulsa", state: "OK", airportCode: "TUL", airportName: "Tulsa International Airport", airportDistanceMiles: 8 },
  { name: "University of Oregon", city: "Eugene", state: "OR", airportCode: "EUG", airportName: "Eugene Airport", airportDistanceMiles: 10 },
  { name: "Oregon State University", city: "Corvallis", state: "OR", airportCode: "PDX", airportName: "Portland International Airport", airportDistanceMiles: 92 },
  { name: "Portland State University", city: "Portland", state: "OR", airportCode: "PDX", airportName: "Portland International Airport", airportDistanceMiles: 11 },
  { name: "Pennsylvania State University", city: "University Park", state: "PA", airportCode: "SCE", airportName: "State College Regional Airport", airportDistanceMiles: 5 },
  { name: "University of Pennsylvania", city: "Philadelphia", state: "PA", airportCode: "PHL", airportName: "Philadelphia International Airport", airportDistanceMiles: 9 },
  { name: "Carnegie Mellon University", city: "Pittsburgh", state: "PA", airportCode: "PIT", airportName: "Pittsburgh International Airport", airportDistanceMiles: 21 },
  { name: "Temple University", city: "Philadelphia", state: "PA", airportCode: "PHL", airportName: "Philadelphia International Airport", airportDistanceMiles: 13 },
  { name: "University of Pittsburgh", city: "Pittsburgh", state: "PA", airportCode: "PIT", airportName: "Pittsburgh International Airport", airportDistanceMiles: 20 },
  { name: "Brown University", city: "Providence", state: "RI", airportCode: "PVD", airportName: "Rhode Island T.F. Green International Airport", airportDistanceMiles: 10 },
  { name: "University of Rhode Island", city: "Kingston", state: "RI", airportCode: "PVD", airportName: "Rhode Island T.F. Green International Airport", airportDistanceMiles: 18 },
  { name: "University of South Carolina", city: "Columbia", state: "SC", airportCode: "CAE", airportName: "Columbia Metropolitan Airport", airportDistanceMiles: 10 },
  { name: "Clemson University", city: "Clemson", state: "SC", airportCode: "GSP", airportName: "Greenville-Spartanburg International Airport", airportDistanceMiles: 44 },
  { name: "College of Charleston", city: "Charleston", state: "SC", airportCode: "CHS", airportName: "Charleston International Airport", airportDistanceMiles: 12 },
  { name: "University of South Dakota", city: "Vermillion", state: "SD", airportCode: "SUX", airportName: "Sioux Gateway Airport", airportDistanceMiles: 52 },
  { name: "South Dakota State University", city: "Brookings", state: "SD", airportCode: "FSD", airportName: "Sioux Falls Regional Airport", airportDistanceMiles: 56 },
  { name: "University of Tennessee", city: "Knoxville", state: "TN", airportCode: "TYS", airportName: "McGhee Tyson Airport", airportDistanceMiles: 13 },
  { name: "Vanderbilt University", city: "Nashville", state: "TN", airportCode: "BNA", airportName: "Nashville International Airport", airportDistanceMiles: 11 },
  { name: "University of Memphis", city: "Memphis", state: "TN", airportCode: "MEM", airportName: "Memphis International Airport", airportDistanceMiles: 7 },
  { name: "Middle Tennessee State University", city: "Murfreesboro", state: "TN", airportCode: "BNA", airportName: "Nashville International Airport", airportDistanceMiles: 28 },
  { name: "University of Texas at Austin", city: "Austin", state: "TX", airportCode: "AUS", airportName: "Austin-Bergstrom International Airport", airportDistanceMiles: 10 },
  { name: "Texas A&M University", city: "College Station", state: "TX", airportCode: "IAH", airportName: "George Bush Intercontinental Airport", airportDistanceMiles: 95 },
  { name: "University of Houston", city: "Houston", state: "TX", airportCode: "HOU", airportName: "William P. Hobby Airport", airportDistanceMiles: 9 },
  { name: "Rice University", city: "Houston", state: "TX", airportCode: "HOU", airportName: "William P. Hobby Airport", airportDistanceMiles: 12 },
  { name: "Texas Tech University", city: "Lubbock", state: "TX", airportCode: "LBB", airportName: "Lubbock Preston Smith International Airport", airportDistanceMiles: 8 },
  { name: "University of North Texas", city: "Denton", state: "TX", airportCode: "DFW", airportName: "Dallas Fort Worth International Airport", airportDistanceMiles: 24 },
  { name: "University of Texas at Dallas", city: "Richardson", state: "TX", airportCode: "DAL", airportName: "Dallas Love Field", airportDistanceMiles: 18 },
  { name: "Baylor University", city: "Waco", state: "TX", airportCode: "AUS", airportName: "Austin-Bergstrom International Airport", airportDistanceMiles: 102 },
  { name: "Southern Methodist University", city: "Dallas", state: "TX", airportCode: "DAL", airportName: "Dallas Love Field", airportDistanceMiles: 5 },
  { name: "University of Texas at San Antonio", city: "San Antonio", state: "TX", airportCode: "SAT", airportName: "San Antonio International Airport", airportDistanceMiles: 9 },
  { name: "University of Utah", city: "Salt Lake City", state: "UT", airportCode: "SLC", airportName: "Salt Lake City International Airport", airportDistanceMiles: 11 },
  { name: "Utah State University", city: "Logan", state: "UT", airportCode: "SLC", airportName: "Salt Lake City International Airport", airportDistanceMiles: 85 },
  { name: "Brigham Young University", city: "Provo", state: "UT", airportCode: "SLC", airportName: "Salt Lake City International Airport", airportDistanceMiles: 50 },
  { name: "University of Vermont", city: "Burlington", state: "VT", airportCode: "BTV", airportName: "Burlington International Airport", airportDistanceMiles: 3 },
  { name: "University of Virginia", city: "Charlottesville", state: "VA", airportCode: "CHO", airportName: "Charlottesville-Albemarle Airport", airportDistanceMiles: 10 },
  { name: "Virginia Tech", city: "Blacksburg", state: "VA", airportCode: "ROA", airportName: "Roanoke-Blacksburg Regional Airport", airportDistanceMiles: 39 },
  { name: "William & Mary", city: "Williamsburg", state: "VA", airportCode: "ORF", airportName: "Norfolk International Airport", airportDistanceMiles: 44 },
  { name: "George Mason University", city: "Fairfax", state: "VA", airportCode: "IAD", airportName: "Washington Dulles International Airport", airportDistanceMiles: 14 },
  { name: "Virginia Commonwealth University", city: "Richmond", state: "VA", airportCode: "RIC", airportName: "Richmond International Airport", airportDistanceMiles: 9 },
  { name: "University of Washington", city: "Seattle", state: "WA", airportCode: "SEA", airportName: "Seattle-Tacoma International Airport", airportDistanceMiles: 19 },
  { name: "Washington State University", city: "Pullman", state: "WA", airportCode: "GEG", airportName: "Spokane International Airport", airportDistanceMiles: 81 },
  { name: "Seattle University", city: "Seattle", state: "WA", airportCode: "SEA", airportName: "Seattle-Tacoma International Airport", airportDistanceMiles: 15 },
  { name: "University of Wisconsin-Madison", city: "Madison", state: "WI", airportCode: "MSN", airportName: "Dane County Regional Airport", airportDistanceMiles: 7 },
  { name: "Marquette University", city: "Milwaukee", state: "WI", airportCode: "MKE", airportName: "Milwaukee Mitchell International Airport", airportDistanceMiles: 8 },
  { name: "University of Wisconsin-Milwaukee", city: "Milwaukee", state: "WI", airportCode: "MKE", airportName: "Milwaukee Mitchell International Airport", airportDistanceMiles: 12 },
  { name: "University of Wyoming", city: "Laramie", state: "WY", airportCode: "DEN", airportName: "Denver International Airport", airportDistanceMiles: 130 },
  { name: "Clemson University College of Engineering", city: "Greenville", state: "SC", airportCode: "GSP", airportName: "Greenville-Spartanburg International Airport", airportDistanceMiles: 14 },
  { name: "Appalachian State University", city: "Boone", state: "NC", airportCode: "CLT", airportName: "Charlotte Douglas International Airport", airportDistanceMiles: 101 },
  { name: "University of Richmond", city: "Richmond", state: "VA", airportCode: "RIC", airportName: "Richmond International Airport", airportDistanceMiles: 11 },
  { name: "Old Dominion University", city: "Norfolk", state: "VA", airportCode: "ORF", airportName: "Norfolk International Airport", airportDistanceMiles: 8 },
  { name: "James Madison University", city: "Harrisonburg", state: "VA", airportCode: "CHO", airportName: "Charlottesville-Albemarle Airport", airportDistanceMiles: 56 },
  { name: "University of Cincinnati Blue Ash College", city: "Blue Ash", state: "OH", airportCode: "CVG", airportName: "Cincinnati/Northern Kentucky International Airport", airportDistanceMiles: 33 },
  { name: "Kent State University", city: "Kent", state: "OH", airportCode: "CLE", airportName: "Cleveland Hopkins International Airport", airportDistanceMiles: 41 },
  { name: "University of Akron", city: "Akron", state: "OH", airportCode: "CAK", airportName: "Akron-Canton Airport", airportDistanceMiles: 15 },
  { name: "Bowling Green State University", city: "Bowling Green", state: "OH", airportCode: "DTW", airportName: "Detroit Metropolitan Wayne County Airport", airportDistanceMiles: 74 },
  { name: "Xavier University", city: "Cincinnati", state: "OH", airportCode: "CVG", airportName: "Cincinnati/Northern Kentucky International Airport", airportDistanceMiles: 18 },
  { name: "University of North Carolina Wilmington", city: "Wilmington", state: "NC", airportCode: "ILM", airportName: "Wilmington International Airport", airportDistanceMiles: 5 },
  { name: "University of North Carolina Charlotte", city: "Charlotte", state: "NC", airportCode: "CLT", airportName: "Charlotte Douglas International Airport", airportDistanceMiles: 11 },
  { name: "University of Louisville School of Medicine", city: "Louisville", state: "KY", airportCode: "SDF", airportName: "Louisville Muhammad Ali International Airport", airportDistanceMiles: 7 },
  { name: "Belmont University", city: "Nashville", state: "TN", airportCode: "BNA", airportName: "Nashville International Airport", airportDistanceMiles: 8 },
  { name: "University of San Francisco", city: "San Francisco", state: "CA", airportCode: "SFO", airportName: "San Francisco International Airport", airportDistanceMiles: 15 },
  { name: "Santa Clara University", city: "Santa Clara", state: "CA", airportCode: "SJC", airportName: "Norman Y. Mineta San Jose International Airport", airportDistanceMiles: 4 },
  { name: "Pepperdine University", city: "Malibu", state: "CA", airportCode: "LAX", airportName: "Los Angeles International Airport", airportDistanceMiles: 22 },
  { name: "Loyola Marymount University", city: "Los Angeles", state: "CA", airportCode: "LAX", airportName: "Los Angeles International Airport", airportDistanceMiles: 4 },
  { name: "Chapman University", city: "Orange", state: "CA", airportCode: "SNA", airportName: "John Wayne Airport", airportDistanceMiles: 10 },
  { name: "University of Denver College of Law", city: "Denver", state: "CO", airportCode: "DEN", airportName: "Denver International Airport", airportDistanceMiles: 26 },
  { name: "Gonzaga University", city: "Spokane", state: "WA", airportCode: "GEG", airportName: "Spokane International Airport", airportDistanceMiles: 10 },
  { name: "Seattle Pacific University", city: "Seattle", state: "WA", airportCode: "SEA", airportName: "Seattle-Tacoma International Airport", airportDistanceMiles: 18 },
  { name: "University of Portland", city: "Portland", state: "OR", airportCode: "PDX", airportName: "Portland International Airport", airportDistanceMiles: 10 },
  { name: "Lewis & Clark College", city: "Portland", state: "OR", airportCode: "PDX", airportName: "Portland International Airport", airportDistanceMiles: 16 },
  { name: "Texas State University", city: "San Marcos", state: "TX", airportCode: "AUS", airportName: "Austin-Bergstrom International Airport", airportDistanceMiles: 34 },
  { name: "University of Texas at Arlington", city: "Arlington", state: "TX", airportCode: "DFW", airportName: "Dallas Fort Worth International Airport", airportDistanceMiles: 14 },
  { name: "University of Texas at El Paso", city: "El Paso", state: "TX", airportCode: "ELP", airportName: "El Paso International Airport", airportDistanceMiles: 10 },
  { name: "Texas Christian University", city: "Fort Worth", state: "TX", airportCode: "DFW", airportName: "Dallas Fort Worth International Airport", airportDistanceMiles: 28 },
  { name: "Sam Houston State University", city: "Huntsville", state: "TX", airportCode: "IAH", airportName: "George Bush Intercontinental Airport", airportDistanceMiles: 63 },
  { name: "University of Alabama in Huntsville", city: "Huntsville", state: "AL", airportCode: "HSV", airportName: "Huntsville International Airport", airportDistanceMiles: 10 },
  { name: "University of South Carolina Upstate", city: "Spartanburg", state: "SC", airportCode: "GSP", airportName: "Greenville-Spartanburg International Airport", airportDistanceMiles: 19 },
  { name: "University of Missouri-Kansas City", city: "Kansas City", state: "MO", airportCode: "MCI", airportName: "Kansas City International Airport", airportDistanceMiles: 24 },
  { name: "University of Nevada, Reno at Lake Tahoe", city: "Incline Village", state: "NV", airportCode: "RNO", airportName: "Reno-Tahoe International Airport", airportDistanceMiles: 34 },
  { name: "University of Arizona Global Campus", city: "Chandler", state: "AZ", airportCode: "PHX", airportName: "Phoenix Sky Harbor International Airport", airportDistanceMiles: 16 },
  { name: "University of Central Oklahoma", city: "Edmond", state: "OK", airportCode: "OKC", airportName: "Will Rogers World Airport", airportDistanceMiles: 23 },
  { name: "Temple University Harrisburg", city: "Harrisburg", state: "PA", airportCode: "MDT", airportName: "Harrisburg International Airport", airportDistanceMiles: 11 },
  { name: "Lehigh University", city: "Bethlehem", state: "PA", airportCode: "EWR", airportName: "Newark Liberty International Airport", airportDistanceMiles: 79 },
  { name: "Villanova University", city: "Villanova", state: "PA", airportCode: "PHL", airportName: "Philadelphia International Airport", airportDistanceMiles: 17 },
  { name: "Drexel University", city: "Philadelphia", state: "PA", airportCode: "PHL", airportName: "Philadelphia International Airport", airportDistanceMiles: 8 },
  { name: "George Washington University", city: "Washington", state: "DC", airportCode: "DCA", airportName: "Ronald Reagan Washington National Airport", airportDistanceMiles: 5 },
  { name: "Georgetown University", city: "Washington", state: "DC", airportCode: "DCA", airportName: "Ronald Reagan Washington National Airport", airportDistanceMiles: 6 },
  { name: "American University", city: "Washington", state: "DC", airportCode: "DCA", airportName: "Ronald Reagan Washington National Airport", airportDistanceMiles: 8 },
  { name: "Howard University", city: "Washington", state: "DC", airportCode: "DCA", airportName: "Ronald Reagan Washington National Airport", airportDistanceMiles: 7 }
];

export const breakTemplates = [
  { breakName: "Fall Break", startDate: "2026-10-15", endDate: "2026-10-18" },
  { breakName: "Thanksgiving", startDate: "2026-11-24", endDate: "2026-11-29" },
  { breakName: "Winter Break", startDate: "2026-12-18", endDate: "2027-01-10" },
  { breakName: "Spring Break", startDate: "2027-03-08", endDate: "2027-03-15" }
];

export const deals = [
  {
    title: "Student Shuttle Bundle",
    description: "Save 15% on shared ride bundles to major airports when traveling in groups of three or more.",
    link: "https://example.com/student-shuttle-bundle",
    expirationDate: "2026-09-01",
    applicableColleges: null
  },
  {
    title: "UniFly Spring Break Promo",
    description: "Split airport rides with a $10 credit for new verified students booking before spring break.",
    link: "https://example.com/spring-break-promo",
    expirationDate: "2027-03-01",
    applicableColleges: null
  },
  {
    title: "Midwest Homebound Discount",
    description: "Reduced flat-rate rides for students heading from Midwest campuses to ORD, MDW, and DTW.",
    link: "https://example.com/midwest-discount",
    expirationDate: "2026-11-15",
    applicableColleges: ["University of Michigan", "Purdue University", "University of Illinois Urbana-Champaign"]
  },
  {
    title: "California Flyer Special",
    description: "Students at select California schools can unlock 20% off airport carpools during finals week.",
    link: "https://example.com/california-flyer",
    expirationDate: "2026-12-10",
    applicableColleges: ["University of California, Los Angeles", "Stanford University", "University of Southern California"]
  },
  {
    title: "East Coast Holiday Ride Match",
    description: "Holiday matching fee waived for trips heading to BOS, JFK, EWR, and PHL before winter break.",
    link: "https://example.com/east-coast-holiday",
    expirationDate: "2026-12-05",
    applicableColleges: null
  }
];

export const sampleUsers = [
  {
    firstName: "Campus",
    lastName: "Admin",
    email: "admin@unifly.edu",
    password: "Admin123!",
    collegeName: "University of Texas at Austin",
    homeAirport: "JFK",
    role: "admin"
  },
  {
    firstName: "Maya",
    lastName: "Thompson",
    email: "maya.thompson@utexas.edu",
    password: "Student123!",
    collegeName: "University of Texas at Austin",
    homeAirport: "JFK",
    role: "student"
  },
  {
    firstName: "Daniel",
    lastName: "Kim",
    email: "daniel.kim@umich.edu",
    password: "Student123!",
    collegeName: "University of Michigan",
    homeAirport: "LAX",
    role: "student"
  },
  {
    firstName: "Aisha",
    lastName: "Patel",
    email: "aisha.patel@unc.edu",
    password: "Student123!",
    collegeName: "University of North Carolina at Chapel Hill",
    homeAirport: "ATL",
    role: "student"
  }
];
